version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      TRADINGS_URL: '3.83.64.54'
      TRADINGS_PORT: '4005'
      TRADINGS_ENTRY: 'tradings'
      PRODUCTS_URL: '3.89.226.210'
      PRODUCTS_PORT: '3000'
      PRODUCTS_ENTRY: 'products'
      STORES_URL: '3.89.226.210'
      STORES_PORT: '4005'
      STORES_ENTRY: 'stores'
      USERS_URL: '3.83.64.54'
      USERS_PORT: '3000'
      USERS_ENTRY: 'courses-ms/resources/courses'
      LOGIN_URL: '3.83.64.54'
      LOGIN_PORT: '3000'
      LOGIN_ENTRY: 'courses-ms/resources/auth'
    ports:
      - '5000:5000'
