version: '2.1'
services:
  api-gateway:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      TRADINGS_URL: '35.193.251.100'
      TRADINGS_PORT: '4005'
      TRADINGS_ENTRY: 'trading'
      PRODUCTS_URL: '35.193.251.100'
      PRODUCTS_PORT: '4006'
      PRODUCTS_ENTRY: 'products'
      STORES_URL: '35.193.251.100'
      STORES_PORT: '3001'
      STORES_ENTRY: 'stores-ms/resources/stores'
      USERS_URL: '35.193.251.100'
      USERS_PORT: '3000'
      USERS_ENTRY: 'courses-ms/resources/courses'
      LOGIN_URL: '35.193.251.100'
      LOGIN_PORT: '3000'
      LOGIN_ENTRY: 'courses-ms/resources/auth'
    ports:
      - '5000:5000'
